# Generated by Django 3.2.6 on 2021-09-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_consumer', '0001_initial'),
        ('sms_transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstransaction',
            name='sms_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smscount', to='sms_consumer.smsuser'),
        ),
    ]
