# Generated by Django 3.2.6 on 2021-09-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_consumer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsuser',
            name='sms_count',
        ),
    ]
