# Generated by Django 3.2.6 on 2021-09-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_consumer', '0002_remove_smsuser_sms_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsuser',
            name='sms_count',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
