# Generated by Django 3.2.7 on 2021-09-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_consumer', '0004_auto_20210923_0555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smslog',
            old_name='msg',
            new_name='message',
        ),
    ]
