# Generated by Django 3.2.7 on 2021-09-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_consumer', '0006_auto_20210923_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smslogmodel',
            name='hello',
        ),
    ]
