# Generated by Django 3.2.7 on 2021-09-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_consumer', '0007_remove_smslogmodel_hello'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslogmodel',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
