# Generated by Django 3.2.7 on 2021-09-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_consumer', '0008_alter_smslogmodel_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslogmodel',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
