# Generated by Django 3.2.7 on 2021-09-24 06:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_consumer', '0011_alter_smslogmodel_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslogmodel',
            name='contact_no',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(verbose_name=models.BigIntegerField()), size=None),
        ),
        migrations.AlterField(
            model_name='smslogmodel',
            name='message',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='smslogmodel',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
